apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-generator-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-generator
    spec:
      serviceAccountName: secret-generator
      containers:
        - name: secret-generator
          image: con2/kubernetes-secret-generator:con2-20181025
          command: ["/kubernetes-secret-generator"]
          args: ["-logtostderr", "-all-namespaces", "-regenerate-insecure"]
